{
 "title": "GPU监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(utilization_gpu, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "显卡使用率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "utilization_gpu{instance=~'$ip'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "显存使用率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "utilization_memory{instance=~'$ip'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "显卡温度",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "temperature_gpu{instance=~'$ip'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "显存使用情况",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "memory_used{instance=~'$ip'}", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}