version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
        prometheus:
                container_name: prometheus
                image: prom/prometheus:v2.19.0
                user: root # https://github.com/prometheus/prometheus/issues/5976
                restart: always
                hostname: prometheus
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
                ports:
                        - 9090:9090
                volumes:
                        - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
                        - ./prometheus:/prometheus
                <<: *logging
