---
- hosts: seal
  tasks:
    - name: tail jsonrpc client.go:186
      shell: tail -n 10 /home/xjgw/sealwork/log/seal.log
      ignore_errors: true
      register: jsonrpc
    - name: print jsonrpc
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address'] 
      when: jsonrpc.stdout.find('jsonrpc/client.go:186') != -1
    - name: restart dminer
      shell: cd /home/xjgw/sealwork/dminer && ./dminer ctl restart dminer
      when: jsonrpc.stdout.find('jsonrpc/client.go:186') != -1

