- name: fix limits
  hosts: all
  tags: limits
  vars:
    LIMITS: "/etc/security/limits.conf"
  tasks:
    - name: hard limits.conf tasks
      become: true
      lineinfile: 
        dest: "{{ LIMITS }}"
        # * hard nofile 1024000
        regex: '^\*\s+hard\s+nofile\s+\d+'
        line: '* hard nofile 1024000'
    - name: soft limits.conf tasks
      become: true
      lineinfile: 
        dest: "{{ LIMITS }}"
        # * soft nofile 1024000
        regex: '^\*\s+soft\s+nofile\s+\d+'
        line: '* soft nofile 1024000'

- name: fix tcp connections
  hosts: all
  tags: sysctl
  become: true
  vars:
    SYSCTL: "/etc/sysctl.conf"
  tasks:
    - name: port range tasks
      #become: true
      lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.ip_local_port_rang'
        line: 'net.ipv4.ip_local_port_range = 32768	60999'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.core.rmem_max'
        line: 'net.core.rmem_max=16777216'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.core.wmem_max'
        line: 'net.core.wmem_max=16777216'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_rmem'
        line: 'net.ipv4.tcp_rmem=4096 87380 16777216'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_wmem'
        line: 'net.ipv4.tcp_wmem=4096 65536 16777216'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_fin_timeout'
        line: 'net.ipv4.tcp_fin_timeout = 10'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_timestamps'
        line: 'net.ipv4.tcp_timestamps = 0'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_window_scaling'
        line: 'net.ipv4.tcp_window_scaling = 0'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_sack'
        line: 'net.ipv4.tcp_sack = 0'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.core.netdev_max_backlog'
        line: 'net.core.netdev_max_backlog = 30000'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_no_metrics_save'
        line: 'net.ipv4.tcp_no_metrics_save=1'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.core.somaxconn'
        line: 'net.core.somaxconn = 262144'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_syncookies'
        line: 'net.ipv4.tcp_syncookies = 0'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_max_orphans'
        line: 'net.ipv4.tcp_max_orphans = 262144'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_max_syn_backlog'
        line: 'net.ipv4.tcp_max_syn_backlog = 262144'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_synack_retries'
        line: 'net.ipv4.tcp_synack_retries = 2'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^net.ipv4.tcp_syn_retries'
        line: 'net.ipv4.tcp_syn_retries = 2'
    - lineinfile: 
        dest: "{{ SYSCTL }}"
        regex: '^fs.file-max'
        line: 'fs.file-max = 6815744'
    - name: sysctl cmd
      raw: sysctl -p
