version: '3.8'

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "2"
      max-size: "500m"


networks:
  monitoring:
    driver: bridge

services:

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    user: $UID:$GID
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/storage'
    restart: always
    ports:
      - 9093:9093
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
    <<: *logging

  alert:
    image: alert
    container_name: alert
    user: $UID:$GID
    volumes:
      - ./alert:/data
    restart: always
    ports:
      - 3030:8080
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
    <<: *logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: $UID:$GID
    volumes:
      - ./prometheus:/etc/prometheus
      - /etc/hosts:/etc/hosts
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/storage'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
    <<: *logging

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    user: $UID:$GID
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-asd456123}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - 8080:3000
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
    <<: *logging
